apiVersion: apps/v1
kind: Deployment
metadata: 
  name: wordpress-frontend
  labels:
    app: web-server
spec:
  selector:
    matchLabels:
      app: frontend-app
  replicas: 1
  template: #for pod definition
    metadata:
      labels:
        app: frontend-app
      
    spec:
      containers:
        - name: front-end
          image: wordpress:latest
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              # value: mysql-service
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: WORDPRESS_DB_HOST
            
            - name: WORDPRESS_DB_USER
              # value: akbardb
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: WORDPRESS_DB_USER

            - name: WORDPRESS_DB_PASSWORD
              # value: akbarpwd
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: WORDPRESS_DB_PASSWORD
            
            - name: WORDPRESS_DB_NAME
              # value: wordpressDB
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: WORDPRESS_DB_NAME


