apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  labels:
    app: mysql-db
spec:
  selector:
    matchLabels:
      app: mysql-db
  replicas: 1
  template: #for pod definition
    metadata:
      labels:
        app: mysql-db

    spec:
      containers:
        - name: mysql-db
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_USER
              value: akbardb

            - name: MYSQL_PASSWORD
              value: akbarpwd

            - name: MYSQL_ROOT_PASSWORD
              value: admin@1234!$
              
            - name: MYSQL_DATABASE
              value: wordpressDB

