apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: "/data/mysql-vol" #volume created on host in our case(minikube)