apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  WORDPRESS_DB_HOST: "mysql-service"
  WORDPRESS_DB_USER: "akbardb"
  WORDPRESS_DB_PASSWORD: "akbarpwd"
  WORDPRESS_DB_NAME: "wordpressDB"

  MYSQL_USER: "akbardb"
  MYSQL_PASSWORD: "akbarpwd"
  MYSQL_ROOT_PASSWORD: "admin@1234!$"
  MYSQL_DATABASE: "wordpressDB"
 